db:
  driver: "postgres"
  dsn: "user=postgres dbname=botastic host=localhost password=postgres sslmode=disable"

openai:
  keys: ["YOUR_KEY"]
  timeout: 10s

sys:
  secret_key: ""
  extra_rate: 0.1
  init_user_credits: 0.1

index_store:
  driver: memory # redis, milvus
  redis:
    address: "localhost:6379"
    password: ""
    db: 0
    key_prefix: app
  milvus:
    address: "localhost:19530"
    collection: indexes
    collection_shards_num: 2

mixpay:
  payee_id: "USER_UUID"
  quote_asset_id: "31d2ea9c-95eb-3355-b65b-ba096853bc18"
  settlement_asset_id: "31d2ea9c-95eb-3355-b65b-ba096853bc18"
  callback_url: "$API_HOST/api/callback/mixpay"
  return_to: ""
  failed_return_to: ""

lemonsqueezy:
  key: ""
  store_id: 12345

topup_variants:
  - name: "$1.00"
    amount: 1.00
  - name: "$5.00"
    amount: 5.00
  - name: "$10.00"
    amount: 10.00
    lemon_id: 123456

twitter:
  api_key: ""
  api_secret: ""
  callback_url: "https://"

order_syncer:
  interval: 1s
  check_interval: 10s
  cancel_interval: 2h

auth:
  jwt_secret: "abc123"
  mixin_client_secret: "...."
  trust_domains:
    - "developers.pando.im"
